# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170512_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='导航条内容')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='指向地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '导航条',
                'verbose_name_plural': '导航条',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
