# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170531_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(upload_to='img/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
