# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170606_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='img/%Y', verbose_name='文章图片'),
        ),
    ]
